### ISSUE TITLE
Failed to open the i2c bus; run as sudo?

### ISSUE THREAD

**Issue by ferazambuja** [bitbank2/CCS811#1]
noob here
I'm running as sudo and still getting the message.
Maybe I compile it wrong? I used make and make -f make_demo

**Comment by bitbank2** [comment]
You haven't provided enough info to help you. Depending on which board you're using, there are several possibilities for the failure. You may have chosen the wrong bus number (usually 0 or 1). You may not have I2C enabled on your board (do a 'ls /dev/i2c*' to see what's available). For Armbian, see the forums for enabling I2C, for Raspbian, use the raspi-config tool to enable it.
