### ISSUE TITLE
ccs811 firmware update

### ISSUE THREAD

**Issue by dmit2k** [bitbank2/CCS811#2]
Hello,

not really an issue, just a question: do you have any experience in updating the sensor board to firmware 2.xx? 

There are instructions for Ardunio boards, but can not find any solution for raspberry...

**Comment by bitbank2** [comment]
I haven't done it before, but it looks pretty simple to do. I found that repo and the code would be pretty simple to convert for use on the Raspberry Pi. I don't have time to work on this at the moment, but it looks easy enough that if it's something you need to do, give it a try.
